# Generated by Django 2.2.10 on 2020-07-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=100)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.Destination')),
            ],
        ),
    ]
